name 'resource-lifecycle'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures resource-lifecycle'
long_description 'Installs/Configures resource-lifecycle'
version '0.1.0'
